// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXKlAMZwb8l2A863s0Odh_nAW4IHF2kso',
    appId: '1:891584307361:android:7d2290de7384810ed010e0',
    messagingSenderId: '891584307361',
    projectId: 'morea-8f840',
    databaseURL: 'https://morea-8f840.firebaseio.com',
    storageBucket: 'morea-8f840.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaNCEZXwSgJgugD5FnCD-OcoN5FvdjLsI',
    appId: '1:891584307361:ios:d9a90621eaab64ead010e0',
    messagingSenderId: '891584307361',
    projectId: 'morea-8f840',
    databaseURL: 'https://morea-8f840.firebaseio.com',
    storageBucket: 'morea-8f840.appspot.com',
    iosClientId: '891584307361-eg7gmf0975qnufrkgmsita1uh4jnf8ij.apps.googleusercontent.com',
    iosBundleId: 'productions.morea.app',
  );
}
